### ISSUE TITLE
Best deviceready method?

### ISSUE THREAD

**Issue by davidpfahler** [Trott/cordova-linter#1]
When I'm developing a PhoneGap app, I usually develop a lot of the time in Chrome, because of the superior debugging. Hence, I cannot use the `deviceready` event to kickstart the app. Rather I'm using a function that wraps cordova API calls and puts them on a queue for (possibly) later execution when the deviceready event fires. One could also use a deferred to do the same.

I'm curious, what are others out there using to combat this problem? What are the implications of waiting for `deviceready` before kickstarting the app? What are the pros and cons of using the method I described above? I hope we can start a discussion here that finally leads to a recommendation for the implementation in this project.

**Comment by Trott** [comment]
I'm archiving this repository, so I'm going to close this issue. Thanks!
